[pytest]
pythonpath = .
addopts = -v -s --alluredir=allure-results
testpaths = tests
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s (%(filename)s:%(lineno)s)